### PR TITLE
Adds h_errno basic support in DCE. The variable is never set yet but at

### PR DESCRIPTION
**Pull request by teto**
least it allows to run more programs yet (for instance iperf3).

### CODE REVIEW

**Comment by teto** [comment]
Hum I am using the new github interface and it seems a few features are buggy, I just forcefully pushed an update but I can't see it here though my change seems to be reflected in the diff.

About your previous comment, I changed the NS_LOG_INFO into a WARN in dce_abort because it made it easier to find why simulation stopped in long logs. Do you want me to revert this line ?

Otherwise this PR is to help loading iperf3  (it doesn't make it work though, someone else found how to make it work but I don't know if I can share his code).

**Comment by thehajime** [comment]
> About your previous comment, I changed the NS_LOG_INFO into a WARN in dce_abort because it made it easier to find why simulation stopped in long logs. Do you want me to revert this line ?

no, it's okay with this change.
 
> Otherwise this PR is to help loading iperf3 (it doesn't make it work though, someone else found how to make it work but I don't know if I can share his code).

please change the commit message to describe so: this patch includes more than h_errno addition.

thanks for the patience.

**Comment by teto** [comment]
I added the explanation about iperf3 launching but not working.

**Comment by thehajime** [comment]
thanks, applied.

**Pull request merged**
