### PR TITLE
Issue 17 - Remove obsolete getcwd warning

### PR DESCRIPTION
**Pull request by teto**
...with gcc pragmas

### CODE REVIEW

**Comment by thehajime** [comment]
Close #17 too. Thanks !

**Comment by thehajime** [comment]
@teto on my Jenkins firm, it shows a build error recently.

http://ns-3-dce.cloud.wide.ad.jp/jenkins/job/daily-dce/label=CentOS6.2-64/686/console

it only happens on Centos6.2. this is probably due to this PR #33. 

could you check it ?

**Comment by teto** [comment]
That was the first time I used pragmas, apparently they should be placed out of the function. I will have a look later.

**Comment by teto** [comment]
Apparently it's because centos runs an older version of GCC, hence:
-either compile with -Wno-unknown-pragmas (as in http://stackoverflow.com/questions/18257854/pragma-gcc-diagnostic-warning-with-gcc) but that may hurt future clang compatibility
- or revert the change and keep the warnings about getwd

**Comment by thehajime** [comment]
I'm fine to revert this patch.

in addition, on Ubuntu 15.04 slave, there is still the warning message like this.

```
[176/413] cxx: test/test-strerror.cc -> build/test/test-strerror.cc.25.o
[177/413] cxx: test/test-stdio.cc -> build/test/test-stdio.cc.26.o
[178/413] cxx: test/test-string.cc -> build/test/test-string.cc.27.o
../test/test-fd-simple.cc: In function ‘void test_cwd()’:
../test/test-fd-simple.cc:320:9: warning: ‘char* getwd(char*)’ is deprecated (declared at /usr/include/unistd.h:525) [-Wdeprecated-declarations]
   cwd = getwd (tmp);
         ^
../test/test-fd-simple.cc:320:19: warning: ‘char* getwd(char*)’ is deprecated (declared at /usr/include/unistd.h:525) [-Wdeprecated-declarations]
   cwd = getwd (tmp);
```

http://ns-3-dce.cloud.wide.ad.jp/jenkins/job/daily-dce/label=Ubuntu1504-64/687/console

circle ci also did.

https://circleci.com/gh/direct-code-execution/ns-3-dce/39

do you see what's going on ?

**Comment by teto** [comment]
The pragmas were to remove these warnings, but maybe the gcc on 15.04 does
not support it ? I believe the diagnostic pragma were added in gcc 4.6.

As for the centos errors, they complain about the place of the pragmas
rather than the pragmas themselves, could this patch help (moving the
pragmas out of lib_dce function)
https://transfer.sh/kV6Y7/test.patch

Matt

2016-02-03 0:19 GMT+01:00 Hajime Tazaki <notifications@github.com>:

> rning: ‘char* getwd(char*)’ is deprecated (declared at
> /usr/include/unistd.h:525) [-Wdeprecated-declara

**Comment by thehajime** [comment]
can't apply the patch (patch --dry-run -p1 < test.patch), it gives ```Only garbage was found in the patch input.`` error.

by applying following patch, it still says

```
[ 15/332] cxx: model/libc-dce.cc -> build/model/libc-dce.cc.6.o
../model/libc-dce.cc:150: warning: expected [error|warning|ignored] after '#pragma GCC diagnostic'
../model/libc-dce.cc:174: warning: expected [error|warning|ignored] after '#pragma GCC diagnostic'
```

```
diff -r daadb2dc4d7c model/libc-dce.cc
--- a/model/libc-dce.cc Thu Jan 28 16:41:09 2016 +0100
+++ b/model/libc-dce.cc Wed Feb 03 17:48:19 2016 +0900
@@ -147,6 +147,9 @@
 
 extern "C" {
 
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
+
 void libc_dce (struct Libc **libc)
 {
   *libc = new Libc;
@@ -168,5 +171,6 @@
   (*libc)->strstr_fn = dce_strstr;
   (*libc)->vsnprintf_fn = dce_vsnprintf;
 }
+#pragma GCC diagnostic pop
 } // extern "C"
 
diff -r daadb2dc4d7c model/libc-ns3.h
--- a/model/libc-ns3.h  Thu Jan 28 16:41:09 2016 +0100
+++ b/model/libc-ns3.h  Wed Feb 03 17:48:19 2016 +0900
@@ -223,11 +223,7 @@
 DCE (exit)
 DCE (getcwd)
 
-#pragma GCC diagnostic push
-#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
 DCE (getwd)
-#pragma GCC diagnostic pop
-
 DCE (get_current_dir_name)
 DCE (chdir)
 DCE (fchdir)
```

**Comment by teto** [comment]
sorry it's quite late here I used "git show" output instead of git diff,
this one should be ok https://transfer.sh/6QGbL/temp.patch

2016-02-03 0:50 GMT+01:00 Hajime Tazaki <notifications@github.com>:

**Comment by thehajime** [comment]
> sorry it's quite late here I used "git show" output instead of git diff,
> this one should be ok https://transfer.sh/6QGbL/temp.patch

okay. take a sleep and see you tomorrow :)

**Comment by thehajime** [comment]
> sorry it's quite late here I used "git show" output instead of git diff,
> this one should be ok https://transfer.sh/6QGbL/temp.patch

tested again with this patch on Centos 6.2 and it said the same.

```
[ 17/332] cxx: model/libc-dce.cc -> build/model/libc-dce.cc.6.o
../model/libc-dce.cc:150: warning: expected [error|warning|ignored] after '#pragma GCC diagnostic'
../model/libc-dce.cc:175: warning: expected [error|warning|ignored] after '#pragma GCC diagnostic'
```

I would like to keep older version of distribution as much as possible but if you think this leads too much load to maintain, I would be fine to make those unsupported.

let me know your opinion.

**Comment by teto** [comment]
The warning now appears also for readdir_r. 
I don't think there is an absolute good solution here. I always heard to stay away from pragma directives. If we could have a flag to selectively disable the warning, I could just add it during my ./waf configure but I don't know if that's possible.

**Comment by thehajime** [comment]
for the moment, do you agree to revert this patchset so that we can support Centos 6.2 ?

**Comment by teto** [comment]
Ok to revert it but then we have to warn user they might need to use "-Wno-deprecated-declarations" as otherwise, the build fails with my compiler "gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2)"

**Comment by teto** [comment]
Should that be in release notes or ?

**Pull request merged**
