### PR TITLE
__init__.py: look for ns3.29/ns3.28 libraries too

### PR DESCRIPTION
**Pull request by teto**
DCE could not find more recent versions of ns3.
Solves #80

### CODE REVIEW

**Comment by teto** [comment]
The PR is blocked on, I think I may need to update bake and/or dce-quagga.
```
[122/409] Compiling myscripts/ns-3-dce-quagga/test/dce-quagga-test.cc
../myscripts/ns-3-dce-quagga/test/dce-quagga-test.cc: In member function 'void ns3::DceQuaggaTestCase::CsmaRxCallback(std::__cxx11::string, ns3::Ptr<const ns3::Packet>)':
../myscripts/ns-3-dce-quagga/test/dce-quagga-test.cc:109:47: error: 'ECHO_REPLY' is not a member of 'ns3::Icmpv4Header'
       if (icmphdr.GetType () == Icmpv4Header::ECHO_REPLY)
                                               ^~~~~~~~~~
```

**Comment by tomhenderson** [comment]
-      if (icmphdr.GetType () == Icmpv4Header::ECHO_REPLY)
+      if (icmphdr.GetType () == Icmpv4Header::ICMPV4_ECHO_REPLY)

**Comment by teto** [comment]
The code was already updated https://github.com/direct-code-execution/ns-3-dce-quagga/blob/master/test/dce-quagga-test.cc#L109. I get dce + ns3 + patches building on nix but for the CI I believe the bake file might be outdated. 
Can't we get rid of https://github.com/direct-code-execution/bake ? and use the upstream one instead ?

**Comment by tomhenderson** [comment]
> Can't we get rid of https://github.com/direct-code-execution/bake ? and use the upstream one instead ?
Yes, I would be in favor of that.

**Comment by teto** [comment]
I have a bit of chicken/egg problem as I get DCE working on nix but they won't let me add the package if I don't use the upstream url but I can't update this repository since tests don't pass.
I've tried to use bake locally but nix breaks every bake assumption (since nix doesn't use FHS and bake doesn't use pkg-config :s ) so it's kinda tough to debug with only the CI.

Right now I have
https://circleci.com/gh/teto/ns-3-dce/135?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification
@tomhenderson I could use some help with bake. I would like to give you the rights for the repository but I don't have the right. Could you open a PR please ?

**Pull request merged**
